<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\BarberOS.Application\BarberOS.Application.csproj" />
    <ProjectReference Include="..\BarberOS.Domain\BarberOS.Domain.csproj" />
  </ItemGroup>

</Project>
